# Copyright 2025-present ScyllaDB
# SPDX-License-Identifier: Apache-2.0

[package]
name = "scylla-usearch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
axum = { version = "*", features = ["macros"] }
bytes = "*"
derive_more = { version = "*", features = ["full"] }
dotenvy = "*"
futures = "*"
itertools = "*"
rayon = "*"
#scylla = "*"
scylla = { git = "https://github.com/smoczy123/scylla-rust-driver.git", branch = "vector-type" }
scylla-cdc = { git = "https://github.com/abastian/scylla-cdc-rust.git", branch = "feature/scylla-0.15.1" }
seastar-rpc = { path = "../seastar-rpc" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["full"] }
tower-http = { version = "*", features = ["full"] }
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
usearch = { git = "https://github.com/unum-cloud/usearch.git" }
utoipa = { version = "*", features = ["axum_extras"] }
utoipa-axum = "*"
utoipa-swagger-ui = { version = "*", features = ["axum"] }
