# Copyright 2026-present ScyllaDB
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.1

"""Tests for node/userdata.sh and provision.userdata_for (quoting, size, syntax, order, the TTL script)."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from vsbenchlib import config, provision  # noqa: E402
from vsbenchlib.proc import VsbenchError  # noqa: E402

USERDATA = config.NODE_SCRIPTS_DIR / "userdata.sh"
SHELLCHECK = shutil.which("shellcheck") or next(
    (str(p) for p in [Path.home() / ".local" / "bin" / "shellcheck"] if p.exists()), None
)
END_MARK = "# --- end generated ---"


def shellcheck(path: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run([str(SHELLCHECK), "-s", "bash", str(path)], capture_output=True, text=True)


def ttl_script() -> str:
    text = USERDATA.read_text()
    start = text.index("<<'TTL_SCRIPT'\n") + len("<<'TTL_SCRIPT'\n")
    return text[start : text.index("\nTTL_SCRIPT\n", start) + 1]


class UserdataForTest(unittest.TestCase):
    def test_header_follows_the_shebang(self) -> None:
        text = provision.userdata_for("scylla", "scylla-0", "c1", 1790000000)
        lines = text.splitlines()
        self.assertEqual(lines[0], "#!/usr/bin/env bash")
        self.assertEqual(lines[1], "# --- generated by vsbench ---")
        header = lines[2 : lines.index(END_MARK)]
        names = ["ROLE", "NODE_NAME", "CLUSTER", "EXPIRES_AT_EPOCH", "NODE_EXPORTER_VERSION", "NODE_EXPORTER_SHA256"]
        self.assertEqual([h.split("=", 1)[0] for h in header], names)
        self.assertIn(f"NODE_EXPORTER_SHA256={config.NODE_EXPORTER_SHA256_ARM64}", header)
        self.assertIn(f"NODE_EXPORTER_VERSION={config.NODE_EXPORTER_VERSION}", header)
        self.assertEqual(text.split(END_MARK + "\n", 1)[1], USERDATA.read_text().split("\n", 1)[1])

    def test_values_with_spaces_quotes_and_dollars_round_trip_without_execution(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            sentinel = Path(tmp) / "pwned"
            tricky = f"a b'c\"d $HOME `touch {sentinel}` $(touch {sentinel}); touch {sentinel}\n\\x"
            text = provision.userdata_for("vs", tricky, "it's $cluster", 7)
            header = text.split(END_MARK)[0]
            script = header + '\nprintf "%s\\0" "$ROLE" "$NODE_NAME" "$CLUSTER" "$EXPIRES_AT_EPOCH"'
            out = subprocess.run(["bash", "-c", script], capture_output=True, text=True, check=True)
            self.assertEqual(out.stdout.split("\0")[:4], ["vs", tricky, "it's $cluster", "7"])
            self.assertFalse(sentinel.exists())

    def test_size_is_below_the_ec2_limit(self) -> None:
        for role in config.ROLES:
            size = len(provision.userdata_for(role, f"{role}-12", "a" * 20, 1790000000).encode())
            self.assertLess(size, provision.USERDATA_LIMIT_BYTES, role)

    def test_oversized_userdata_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            Path(tmp, "userdata.sh").write_text("#!/usr/bin/env bash\n" + "#" * 17000 + "\n")
            with mock.patch.object(config, "NODE_SCRIPTS_DIR", Path(tmp)):
                with self.assertRaisesRegex(VsbenchError, "16384"):
                    provision.userdata_for("vs", "vs-0", "c1", 1)

    def test_unknown_role_is_rejected(self) -> None:
        with self.assertRaises(VsbenchError):
            provision.userdata_for("db", "db-0", "c1", 1)

    def test_bash_syntax_of_the_assembled_userdata(self) -> None:
        for role in config.ROLES:
            text = provision.userdata_for(role, f"{role}-0", "c1", 1790000000)
            result = subprocess.run(["bash", "-n"], input=text, capture_output=True, text=True)
            self.assertEqual(result.returncode, 0, f"{role}: {result.stderr}")

    def test_shellcheck_static_and_assembled(self) -> None:
        if not SHELLCHECK:
            self.skipTest("SHELLCHECK MISSING: install shellcheck (~/.local/bin/shellcheck) to lint node/userdata.sh")
        with tempfile.TemporaryDirectory() as tmp:
            assembled = Path(tmp, "userdata-client.sh")
            assembled.write_text(provision.userdata_for("client", "client", "c1", 1790000000))
            ttl = Path(tmp, "vsbench-ttl")
            ttl.write_text(ttl_script())
            for path in (USERDATA, assembled, ttl):
                result = shellcheck(path)
                self.assertEqual(result.returncode, 0, f"{path.name}:\n{result.stdout}")


class UserdataOrderTest(unittest.TestCase):
    """The TTL must be armed before anything that can fail on the network, apt or disks."""

    def setUp(self) -> None:
        self.text = USERDATA.read_text()

    def pos(self, needle: str) -> int:
        self.assertIn(needle, self.text)
        return self.text.index(needle)

    def test_critical_order(self) -> None:
        steps = [
            "set -Eeuo pipefail",
            'exec > >(tee -a "$LOG_FILE") 2>&1',
            "trap 'on_failure",
            ': "${ROLE:?}"',
            "systemctl enable --now vsbench-ttl.timer",
            "systemctl disable --now unattended-upgrades.service apt-daily.timer apt-daily-upgrade.timer",
            "/etc/docker/daemon.json <<'JSON'",
            'apt_get install "${packages[@]}"',
            "sysctl -e -p /etc/sysctl.d/99-vsbench.conf",
            "sha256sum -c -",
            "systemctl enable --now node-exporter.service",
            "scylla) setup_scylla_disks ;;",
            'install -d -o ubuntu -g ubuntu -m 0755 "$VSB_HOME/$dir"',
            'touch "$READY_MARKER"',
        ]
        positions = [self.pos(step) for step in steps]
        self.assertEqual(positions, sorted(positions))
        before_ttl = self.text[: self.pos("systemctl enable --now vsbench-ttl.timer")]
        before_ttl = before_ttl.split("# --- 1. TTL", 1)[0]  # the TTL script itself is a quoted heredoc
        for network_step in ("curl ", "apt-get", "apt_get "):
            self.assertNotIn(network_step, before_ttl)

    def test_paths_match_config(self) -> None:
        self.assertIn(f"VSB_HOME={config.NODE_HOME}\n", self.text)
        self.assertEqual(config.NODE_READY_MARKER, f"{config.NODE_HOME}/ready")
        self.assertEqual(config.NODE_FAILED_MARKER, f"{config.NODE_HOME}/failed")
        self.assertIn("READY_MARKER=$VSB_HOME/ready\n", self.text)
        self.assertIn("FAILED_MARKER=$VSB_HOME/failed\n", self.text)
        self.assertIn(f"EXPIRES_FILE={config.NODE_EXPIRES_FILE}\n", self.text)
        self.assertIn(f"LOG_FILE={provision.USERDATA_LOG}\n", self.text)
        for sub in ("scripts", "jobs", "bench", "datasets", "monitoring"):
            self.assertIn(sub, self.text.split("# --- 8. working directories")[1])

    def test_apt_timer_docker_and_node_exporter_settings(self) -> None:
        for needle in (
            "NEEDRESTART_MODE=l",
            "-o DPkg::Lock::Timeout=600 -o Acquire::Retries=5",
            '"live-restore": true',
            '"max-size": "200m", "max-file": "5"',
            "OnBootSec=1min",
            "OnUnitActiveSec=1min",
            "AccuracySec=10s",
            "Type=oneshot",
            "--collector.ethtool",
            "pps_allowance_exceeded|conntrack_allowance_exceeded|conntrack_allowance_available",
            "--collector.interrupts",
            "--no-collector.hwmon --no-collector.thermal_zone --no-collector.rapl",
            "^(vector-store|docker)[.]service$$",  # systemd needs $$ for a literal $
            "Amazon EC2 NVMe Instance Storage",
            "mkfs.xfs -f -K -m rmapbt=0 -m reflink=0",
            "noatime,discard,lazytime,nofail",
            "packages+=(xfsprogs mdadm nvme-cli)",
            'apt_get install sysstat linux-tools-common "linux-tools-$(uname -r)" ||',  # perf, best effort
        ):
            self.assertIn(needle, self.text)


class TtlScriptTest(unittest.TestCase):
    """Runs the embedded /usr/local/sbin/vsbench-ttl with fake logger/wall/systemctl."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp)
        self.script = self.tmp / "vsbench-ttl"
        self.script.write_text(ttl_script())
        self.bin, self.calls_log = self.tmp / "bin", self.tmp / "calls.log"
        self.bin.mkdir()
        for tool in ("logger", "wall", "systemctl"):
            fake = self.bin / tool
            fake.write_text(f'#!/usr/bin/env bash\necho "{tool} $*" >> "{self.calls_log}"\n')
            fake.chmod(0o755)
        self.expires = self.tmp / "expires_at"
        self.env = os.environ | {"PATH": f"{self.bin}:{os.environ['PATH']}", "VSBENCH_TTL_DRY_RUN": "1"}
        self.env |= {"VSBENCH_TTL_EXPIRES_FILE": str(self.expires), "VSBENCH_TTL_STATE_DIR": str(self.tmp)}

    def run_ttl(self, expires: str | None = None, lastgood: str | None = None) -> str:
        if expires is not None:
            self.expires.write_text(expires)
        if lastgood is not None:
            (self.tmp / "ttl.lastgood").write_text(lastgood)
        result = subprocess.run(["bash", str(self.script)], env=self.env, capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        return result.stdout

    def logged(self) -> str:
        return self.calls_log.read_text() if self.calls_log.exists() else ""

    def test_future_expiry_keeps_running_and_updates_lastgood(self) -> None:
        future = str(int(time.time()) + 7200)
        out = self.run_ttl(f"{future}\n", "1")
        self.assertNotIn("poweroff", out)
        self.assertEqual((self.tmp / "ttl.lastgood").read_text().strip(), future)
        self.assertEqual(self.logged(), "")

    def test_past_expiry_powers_off(self) -> None:
        out = self.run_ttl(str(int(time.time()) - 5), str(int(time.time()) + 7200))
        self.assertIn("DRY-RUN poweroff", out)
        self.assertIn("wall vsbench: TTL expired", self.logged())
        self.assertNotIn("systemctl", self.logged())  # dry run

    def test_invalid_file_falls_back_to_lastgood(self) -> None:
        future = str(int(time.time()) + 7200)
        for bad in ("17900", "not-a-number", future + "9", ""):  # truncated, garbage, too long, empty
            out = self.run_ttl(bad, future)
            self.assertNotIn("poweroff", out, bad)
        self.assertEqual(self.logged().count("invalid or missing"), 4)
        self.assertEqual((self.tmp / "ttl.lastgood").read_text().strip(), future)
        self.expires.unlink()
        self.assertIn("DRY-RUN poweroff", self.run_ttl(None, str(int(time.time()) - 1)))

    def test_no_valid_value_at_all_powers_off(self) -> None:
        out = self.run_ttl("", "garbage")
        self.assertIn("no valid expiry at all", out)
        self.assertIn("DRY-RUN poweroff", out)

    def test_warns_once_per_threshold(self) -> None:
        soon = str(int(time.time()) + 20 * 60)
        self.run_ttl(soon, soon)
        self.run_ttl(soon, soon)
        self.assertEqual(self.logged().count("wall vsbench: this node powers off"), 1)
        sooner = str(int(time.time()) + 8 * 60)
        self.run_ttl(sooner)
        self.assertEqual(self.logged().count("wall vsbench: this node powers off"), 2)


if __name__ == "__main__":
    unittest.main()
