# Copyright 2026-present ScyllaDB
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.1

"""Benchmark jobs on the client: step scripts, start/follow/wait, and finalize_job().

A job is a step script (`step NAME -- CMD` lines; node/bench-job.sh) in NODE_JOBS/<id>/steps.sh.
finalize_job() (idempotent, also run by `job wait`) turns its log into results records and state
changes. Split from bench.py, which re-exports every name used elsewhere.
"""

from __future__ import annotations

import collections
import contextlib
import re
import shlex
import sys
import time
from collections.abc import Callable, Sequence
from typing import Any, NoReturn

from . import config, proc, prom, remote, results
from . import state as st
from .proc import PreconditionError, StillRunning, VsbenchError
from .state import State

KEYSPACE, TABLE, CLIENT = "vsb_keyspace", "vsb_table", "client"
STEP_LIB = "bench-job.sh"
ERROR_TAIL_LINES = 50
FINALIZE_RESERVE_S = 60  # of a command's foreground budget, kept for finalizing (records, Prometheus)
PHASES = ("fetch", "buckets", "table", "index")
STEP_PHASES = {"fetch": "fetch", "buckets": "buckets", "clear-buckets": "buckets", "build-table": "table"}
STEP_PHASES["build-index"] = "index"
FINAL_STATUSES = ("finalized", "failed")
CONCURRENT_KINDS = ("churn",)  # jobs the other bench commands may run next to (see churn.py)
FAILURE_HINTS = {
    "ALLOW FILTERING": "--bucket needs a local index (vsbench bench load <dataset> --local-index)",
    "Global ANN query is not supported": "the index is local: search-cql needs --bucket N",
    "list array": "a parquet file uses 32-bit lists and needs conversion (reference.md#datasets)",
}
_BEGIN_RE = re.compile(r"^=== VSBENCH STEP BEGIN (\S+) ")
_END_RE = re.compile(r"^=== VSBENCH STEP END (\S+) (-?\d+) ")
_CPUSET_RE = re.compile(r"^vsbench: cpuset=(\S+)", re.MULTILINE)
_OWN_LINES = ("=== VSBENCH ", "vsbench: cpuset=")  # job/step markers, not tool output


# --- Step scripts ---------------------------------------------------------------------------
def _quote(word: str) -> str:
    if "\n" not in word:
        return shlex.quote(word)
    return "$'" + word.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"


def step_line(name: str, argv: Sequence[str], timeout_s: int | None = None) -> str:
    words = ["step", name, *(["--timeout", f"{timeout_s}s"] if timeout_s else []), "--", *argv]
    return " ".join(_quote(str(word)) for word in words)


def job_script(job_id: str, kind: str, steps: Sequence[str]) -> str:
    header = ["#!/usr/bin/env bash", f"# vsbench {kind} job {job_id}; generated by bench.py, see node/{STEP_LIB}."]
    header += ["set -euo pipefail", f"source {_quote(f'{config.NODE_SCRIPTS}/{STEP_LIB}')}"]
    return "\n".join([*header, *steps]) + "\n"


def options_mismatch(requested: dict[str, str], effective: dict[str, Any]) -> dict[str, list[Any]]:
    """{key: [requested, effective]} for requested options that Vector Store reports differently."""

    def same(a: Any, b: Any) -> bool:
        with contextlib.suppress(TypeError, ValueError):
            return float(a) == float(b)
        return str(a).strip().lower() == str(b).strip().lower()

    return {k: [v, effective[k]] for k, v in requested.items() if k in effective and not same(v, effective[k])}


# --- Start, follow, wait ------------------------------------------------------------------------
def follow_budget(timeout_s: int, started: float) -> int:
    """Seconds left to follow a job: the command's foreground budget counted from `started`
    (time.monotonic()) minus a reserve for finalizing, so the whole command ends within the budget."""
    reserve = min(FINALIZE_RESERVE_S, max(0, timeout_s) // 4)
    return max(1, int(timeout_s - reserve - (time.monotonic() - started)))


def _with_job(state: State, job_id: str, entry: dict[str, Any]) -> State:
    return {**state, "jobs": {**(state.get("jobs") or {}), job_id: entry}}


def _job(state: State, job_id: str) -> dict[str, Any]:
    if job_id not in (state.get("jobs") or {}):
        raise VsbenchError(f"unknown job '{job_id}'", f"list jobs with: vsbench -c {state.get('cluster')} job list")
    return state["jobs"][job_id]


def _start_job(cluster: str, job_id: str, kind: str, steps: Sequence[str], params: dict[str, Any], **kw: Any) -> None:
    """Upload the steps, record the job (and kw change(state)) in the state, start it; kw scripts: node scripts."""
    change = kw.get("change") or (lambda s: s)
    local = st.paths(cluster).work_dir / "jobs" / f"{job_id}.sh"
    proc.atomic_write(local, job_script(job_id, kind, steps))
    for name in (STEP_LIB, *kw.get("scripts", ())):
        remote.ensure_script(cluster, CLIENT, name)
    script = f"{remote.job_dir(job_id)}/steps.sh"
    remote.upload(cluster, CLIENT, local, script, sudo=False, mode="0644")
    entry = {"kind": kind, "node": CLIENT, "started_at": proc.iso(proc.utcnow()), "params": params, "status": "running"}
    st.update(cluster, lambda s: _with_job(change(s), job_id, entry))
    try:
        remote.job_start(cluster, CLIENT, job_id, script=script)
    except VsbenchError as err:
        failed = {**entry, "status": "failed", "error": str(err)[:300]}
        st.update(cluster, lambda s: _with_job(s, job_id, failed))
        raise
    proc.log(f"started job {job_id} on {CLIENT} ({len(steps)} steps)")


def _line_printer(job_id: str, raw_output: bool, on_step: Callable[[str], None] | None = None) -> Callable[[str], None]:
    """raw: the tool's output on stdout; -v: the log on stderr; else step starts/failures, `vsbench:` lines.
    `on_step` gets the name of every step as it begins (bench.profile_trigger)."""

    def on_line(line: str) -> None:
        ours, begin, end = line.startswith(_OWN_LINES), _BEGIN_RE.match(line), _END_RE.match(line)
        if begin and on_step is not None:
            on_step(begin.group(1))
        if raw_output and not ours:
            print(line, flush=True)
        elif proc.VERBOSE and not raw_output:
            sys.stderr.write(line + "\n")
        elif begin and not raw_output:
            proc.log(f"{job_id}: step {begin.group(1)}")
        elif end and end.group(2) != "0":
            proc.log(f"{job_id}: step {end.group(1)} failed (exit {end.group(2)})")
        elif line.startswith("vsbench: ") and not ours and not raw_output:
            proc.log(f"{job_id}: {line.removeprefix('vsbench: ')}")

    return on_line


def _follow(
    cluster: str, job_id: str, timeout_s: int, raw_output: bool = False, on_step: Callable[[str], None] | None = None
) -> int:
    node = _job(st.require(cluster), job_id)["node"]
    try:
        return remote.job_follow(cluster, node, job_id, timeout_s, _line_printer(job_id, raw_output, on_step))
    except (StillRunning, remote.JobNotFound):
        raise
    except VsbenchError:
        with contextlib.suppress(VsbenchError):
            if remote.job_poll(cluster, node, job_id, 0, max_bytes=1).lost:
                finalize_job(cluster, job_id)  # record the loss; the error explains it
        raise


def _failure_text(job: dict[str, Any]) -> str:
    where = f" in step {job['failed_step']}" if job.get("failed_step") else ""
    return f"{where}: {job.get('error') or 'no error recorded'}"


def _warn_if_failed(cluster: str, job_id: str) -> None:
    job = (st.require(cluster).get("jobs") or {}).get(job_id) or {}
    if job.get("status") == "failed":
        detail = f"vsbench -c {cluster} job wait {job_id}"
        proc.warn(f"the earlier job {job_id} ({job.get('kind')}) failed{_failure_text(job)} (details: {detail})")


def _ensure_idle(cluster: str) -> State:  # finalize ended jobs (warn about failed ones); refuse while one runs
    for job_id, job in (st.require(cluster).get("jobs") or {}).items():
        if job.get("status") != "running":
            continue
        try:
            progress = remote.job_poll(cluster, job["node"], job_id, 0, max_bytes=1)
        except remote.JobNotFound:
            gone = {**job, "status": "failed", "error": "the job is not on the node"}
            st.update(cluster, lambda s, j=job_id, e=gone: _with_job(s, j, e))
            _warn_if_failed(cluster, job_id)
            continue
        if progress.running and progress.exit_code is None:
            if job.get("kind") in CONCURRENT_KINDS:  # a churn stream is meant to run under the other commands
                continue
            hint = f"vsbench -c {cluster} job wait {job_id} (or stop it: vsbench -c {cluster} job cancel {job_id})"
            raise PreconditionError(f"job {job_id} ({job.get('kind')}) is still running on {job['node']}", hint)
        proc.log(f"finalizing the earlier job {job_id}")
        try:
            finalize_job(cluster, job_id)
        except VsbenchError as err:
            proc.warn(f"could not finalize job {job_id}: {err}")
            continue
        _warn_if_failed(cluster, job_id)
    return st.require(cluster)


def _raise_failed(cluster: str, job_id: str, job: dict[str, Any], records: list[dict], code: int | None) -> NoReturn:
    """The error of a failed job, the same whether this call or an earlier one finalized it."""
    where, error = (f" in step {job['failed_step']}" if job.get("failed_step") else ""), job.get("error")
    if code is None:
        message = f"job {job_id} failed{where} without an exit code: {error or 'it was lost'}"
    elif code:
        message = f"job {job_id} failed{where} (exit {code}): {error}"
    else:
        message = f"{job_id}: {error}"
    hints = [f"log: vsbench -c {cluster} job logs {job_id} --tail 50"]
    hints += [hint for text, hint in FAILURE_HINTS.items() if text in str(error)]
    good = [r for r in records if r.get("exit") == 0 and str(r.get("kind")).startswith("search-")]
    hints += [f"{len(good)} run(s) were recorded: vsbench -c {cluster} results --series {job_id}"] if good else []
    raise VsbenchError(message + (" (the step reached its timeout)" if code == 124 else ""), "; ".join(hints))


def job_wait(
    cluster: str,
    job_id: str,
    timeout_s: int,
    *,
    started: float | None = None,
    on_step: Callable[[str], None] | None = None,
) -> list[dict[str, Any]]:
    """Follow a job, finalize it, return its records; raise if it failed (also when an earlier command
    finalized it). timeout_s is the foreground budget counted from `started` (time.monotonic(), default
    now), including a finalize reserve; StillRunning when the job outlives it."""
    started = time.monotonic() if started is None else started
    job = _job(st.require(cluster), job_id)
    if job.get("status") in FINAL_STATUSES:
        records = finalize_job(cluster, job_id)
        if job.get("status") == "failed":
            _raise_failed(cluster, job_id, job, records, job.get("exit_code"))
        return records
    budget = follow_budget(timeout_s, started)
    code = _follow(cluster, job_id, budget, raw_output=job.get("kind") == "raw", on_step=on_step)
    records = finalize_job(cluster, job_id)
    job = _job(st.require(cluster), job_id)
    if code == 0 and not job.get("error"):
        return records
    _raise_failed(cluster, job_id, job, records, code)


# --- Finalize ---------------------------------------------------------------------------------
_Outcome = collections.namedtuple("_Outcome", "job_id job log exit_code ended_at sections failed_step error cpuset")
Finalized = tuple[list[dict[str, Any]], Callable[[State], State] | None, str | None]


def _error_of(text: str) -> str | None:
    parsed = results.parse_bench_log(text)
    lines = [line for line in results.strip_ansi(text).splitlines() if "error" in line.lower()]
    return str(parsed["errors"][0]) if parsed["errors"] else (lines[-1].strip()[:300] if lines else None)


def _outcome(job_id: str, job: dict[str, Any], log: str, progress: remote.JobProgress) -> _Outcome:
    sections, code = tuple(results.step_sections(log)), progress.exit_code
    failed = next((s for s in sections if s["exit"] != 0), None)
    if failed is not None:
        error = _error_of(failed["text"]) or f"exit {failed['exit'] if failed['exit'] is not None else code}"
    elif code is None:
        error = "the job stopped without an exit code (killed, out of memory, or the node rebooted)"
    else:
        error = None if code == 0 else _error_of(log) or f"exit {code}"
    cpuset = match.group(1) if (match := _CPUSET_RE.search(log)) else None
    return _Outcome(job_id, job, log, code, progress.ended_at, sections, failed and failed["name"], error, cpuset)


def finalize_job(cluster: str, job_id: str) -> list[dict[str, Any]]:
    """Record a finished job's results and state changes; idempotent (returns the recorded results)."""
    job = _job(st.require(cluster), job_id)
    if job.get("status") in FINAL_STATUSES:
        wanted = set(job.get("run_ids") or [])
        return [r for r in results.load_records(cluster) if r.get("run_id") in wanted] if wanted else []
    progress = remote.job_poll(cluster, job["node"], job_id, 0, max_bytes=1)
    if progress.exit_code is None and progress.running:
        raise PreconditionError(f"job {job_id} is still running", f"wait: vsbench -c {cluster} job wait {job_id}")
    out = _outcome(job_id, job, remote.job_log(cluster, job["node"], job_id, None), progress)
    results.save_log(cluster, job_id, out.log)
    finalizers = {"load": _finalize_build, "index": _finalize_build, "search": _finalize_search}
    finalizer = {**finalizers, "churn": _finalize_churn}.get(job["kind"])
    records, change, problem = finalizer(cluster, st.require(cluster), out) if finalizer else ([], None, None)
    for record in records:  # records first: a crash before the state update only repeats this
        results.append(cluster, record)
    done = {"status": "failed" if problem or out.error else "finalized", "exit_code": out.exit_code}
    done.update(ended_at=out.ended_at, failed_step=out.failed_step, error=problem or out.error)
    done.update(finalized_at=proc.iso(proc.utcnow()), run_ids=[r["run_id"] for r in records])
    change = change or (lambda s: s)
    st.update(cluster, lambda s: _with_job(change(s), job_id, {**(s.get("jobs") or {}).get(job_id, job), **done}))
    return records


def _tail(text: str) -> str:
    return "\n".join(results.strip_ansi(text).splitlines()[-ERROR_TAIL_LINES:])


def _built_load(cluster: str, state: State, out: _Outcome) -> tuple[dict[str, Any], dict[str, Any]]:
    """(state.load after a load/index job, option mismatches); effective options come from vs-0."""
    params, load = out.job["params"], {**(state.get("load") or {}), "pending_job": None}
    done = {STEP_PHASES[s["name"]]: s["end"] for s in out.sections if s["name"] in STEP_PHASES and s["exit"] == 0}
    load["phases"] = {**(load.get("phases") or {}), **done}
    if "index" not in done:
        return load, {}
    url = f"http://{st.nodes(state, 'vs')[0].get('private_ip')}:{config.PORT_VS}/api/v1/indexes/{KEYSPACE}/"
    try:
        effective = remote.http_json(cluster, CLIENT, url + params["index"]).get("options")
    except (VsbenchError, AttributeError) as err:
        proc.warn(f"could not read the effective index options: {str(err).splitlines()[0]}")
        effective = None
    mismatch = options_mismatch(params["requested"], effective) if isinstance(effective, dict) else {}
    load.update(index_options=effective, options_ok=None if effective is None else not mismatch)
    return {**load, "loaded_at": done["index"] if out.job["kind"] == "load" else load.get("loaded_at")}, mismatch


def _finalize_build(cluster: str, state: State, out: _Outcome) -> Finalized:  # load and index jobs
    params, (load, mismatch), took = out.job["params"], _built_load(cluster, state, out), {}
    for section in out.sections:
        took.update(results.parse_bench_log(section["text"])["took"])
    extra = {"run_id": out.job_id, "series_id": out.job_id, "started_at": out.job.get("started_at")}
    extra.update(ended_at=out.ended_at, exit=-1 if out.exit_code is None else out.exit_code)
    extra.update(log=f"results/{out.job_id}.log", index_name=params["index"])
    if out.exit_code != 0:
        extra.update(error_tail=_tail(out.log), error=out.error, failed_step=out.failed_step)
    details = {"index_name": params["index"], "requested_options": params["index_options"], "rows": load.get("rows")}
    details.update(options_mismatch=mismatch or None, build_index_s=took.get("build_index_s"), phases=params["todo"])
    details.update(upload_s=took.get("build_table_s"), index_s=took.get("build_index_s"))
    details.update(drop_index_s=took.get("drop_index_s"), previous_index=params["old_index"])
    vs_build = ((state.get("deployed") or {}).get("vector_store") or {}).get("build_id")
    details.update(trigger=f"bench {out.job['kind']}", build_id=vs_build)
    kind = "load" if out.job["kind"] == "load" else "index-build"
    extra["load" if kind == "load" else "index_build"] = details
    keys = ("rf", "concurrency", "local_index", "index_options", "resume", "index_timeout_s")
    record_params, view = {k: params.get(k) for k in keys}, {**state, "load": load}
    record = results.make_record(kind, view, record_params, None, None, None, extra)
    detail = ", ".join(f"{k}: requested {v[0]}, in effect {v[1]}" for k, v in mismatch.items())
    problem = f"Vector Store ignored index options ({detail}); invalid values fall back to defaults" if detail else None
    mine = out.job_id  # keep state.load unless a newer job has taken it over
    return [record], lambda s: {**s, "load": load} if (s.get("load") or {}).get("pending_job") == mine else s, problem


_CHURN_RE = re.compile(r"(rows issued|rows acked|rows failed|last vector_id|insert rate): (\S+)")


def _finalize_churn(cluster: str, state: State, out: _Outcome) -> Finalized:
    """One record of kind "churn" from insert-rows' summary lines; the acked rows are added to
    state.load.churn_rows when the load is still the one the stream went into."""
    params, text = out.job["params"], out.sections[0]["text"] if out.sections else out.log
    found = dict(_CHURN_RE.findall(results.strip_ansi(text)))
    counts = {k: int(found[v]) if found.get(v, "").isdigit() else None for k, v in _CHURN_COUNTS.items()}
    rate = found.get("insert rate", "").split("/")[0]
    details = {k: params.get(k) for k in ("rate", "duration_s", "concurrency", "start_id", "dimension")}
    details.update(counts, achieved_rate=float(rate) if rate.replace(".", "", 1).isdigit() else None)
    extra: dict[str, Any] = {"run_id": out.job_id, "series_id": out.job_id, "label": params.get("label")}
    extra.update(started_at=out.job.get("started_at"), ended_at=out.ended_at, index_name=params["index"])
    extra.update(exit=-1 if out.exit_code is None else out.exit_code, log=f"results/{out.job_id}.log", churn=details)
    if out.exit_code != 0:
        extra.update(error_tail=_tail(out.log), error=out.error, failed_step=out.failed_step)
    elif counts["rows_acked"] is None:
        extra.update(error="no insert-rows summary in the log", error_tail=_tail(out.log))
    view = {**state, "load": (params.get("snapshot") or {}).get("load") or state.get("load")}
    window = (out.job.get("started_at"), out.ended_at) if out.job.get("started_at") and out.ended_at else None
    record_params = {k: params.get(k) for k in ("rate", "duration_s", "concurrency", "extra_args")}
    record = results.make_record("churn", view, record_params, None, None, window, extra)
    acked = counts["rows_acked"] or 0

    def change(s: State) -> State:
        load = s.get("load") or {}
        if load.get("index") != params["index"]:
            return s
        return {**s, "load": {**load, "churn_rows": int(load.get("churn_rows") or 0) + acked}}

    return [record], change if acked else None, extra.get("error") if out.exit_code == 0 else None


_CHURN_COUNTS = {"rows_issued": "rows issued", "rows_acked": "rows acked", "rows_failed": "rows failed"}
_CHURN_COUNTS["last_id"] = "last vector_id"


def _search_record(cluster: str, view: State, out: _Outcome, item: dict[str, Any], step: dict[str, Any]) -> dict:
    # The record of one measured run; `step` is its log section, or its failed warmup's.
    params, run_id = out.job["params"], f"{out.job_id}-{item['name'].removeprefix('search-')}"
    code = step["exit"] if step["exit"] is not None else (out.exit_code or -1)
    parsed = results.parse_bench_log(step["text"])
    measured = step["name"] == item["name"] and code == 0 and parsed["qps"] is not None
    window = (parsed["started_at"], parsed["gathering_at"]) if parsed["started_at"] and parsed["gathering_at"] else None
    server, server_error = None, "no measurement window in the log" if measured else "the run failed"
    if measured and window and not (view.get("deployed") or {}).get("monitoring"):
        server_error = "monitoring is not deployed"
    elif measured and window:
        try:  # best effort: a missing server side never loses the client result
            server, server_error = prom.server_metrics(cluster, *window, KEYSPACE, params["index"], view), None
        except VsbenchError as err:
            server_error = str(err).splitlines()[0]
    extra = {"run_id": run_id, "series_id": out.job_id, "repeat_index": item["repeat_index"], "exit": code}
    extra.update({key: params.get(key) for key in ("comparison_id", "arm", "label", "index_options", "vs_engine")})
    extra.update(started_at=step["begin"], ended_at=step["end"], server_metrics_error=server_error)
    extra.update(index_name=params.get("index"), log=results.save_log(cluster, run_id, step["text"]))
    profile = _pull_profiles(cluster, run_id, (params.get("profiles") or {}).get(item["name"]) or {})
    extra.update({"profile": profile} if profile else {})
    if churned := (view.get("load") or {}).get("churn_rows"):  # rows bench churn added to the base table
        extra["churn_rows"] = churned
    if not measured:
        error = _error_of(step["text"]) or ("no measurements in the log" if code == 0 else f"exit {code}")
        extra.update(error_tail=_tail(step["text"]), error=error, failed_step=step["name"])
    record_params = {key: params.get(key) for key in ("limit", "duration_s", "warmup_s", "bucket")}
    record_params.update(concurrency=item["concurrency"], extra_args=params.get("extra_args") or [], cpuset=out.cpuset)
    kind, client, window = f"search-{params['kind']}", parsed if measured else None, window if measured else None
    return results.make_record(kind, view, record_params, client, server, window, extra)


PROFILE_FILES = ("perf.txt", "perf-dso.txt", "pidstat.txt")
PROFILE_WAIT_S = 45  # a capture still rendering its reports after this is recorded as an error


def _pull_profiles(cluster: str, run_id: str, jobs: dict[str, str]) -> dict[str, Any]:
    """{node: {job_id, dir, files | error}}: the reports of the run's profile jobs, downloaded into
    results/artifacts/profiles/<run_id>/<node>/. A failure never loses the result."""
    paths, profile = st.paths(cluster), {}
    for node, pjob in jobs.items():
        local_dir = paths.results_dir / "artifacts" / "profiles" / run_id / node
        info: dict[str, Any] = {"job_id": pjob, "dir": str(local_dir.relative_to(paths.root))}
        try:
            _wait_profile(cluster, node, pjob)
            for name in PROFILE_FILES:
                remote.download(cluster, node, f"{remote.job_dir(pjob)}/profile/{name}", local_dir / name)
            info["files"] = list(PROFILE_FILES)
        except VsbenchError as err:
            info["error"] = str(err).splitlines()[0]
        profile[node] = info
    return profile


def _wait_profile(cluster: str, node: str, pjob: str) -> None:
    deadline, where = time.monotonic() + PROFILE_WAIT_S, f"{remote.job_dir(pjob)}/profile"
    while True:
        progress = remote.job_poll(cluster, node, pjob, 0, max_bytes=1)
        if progress.exit_code is not None:
            if progress.exit_code != 0:
                raise VsbenchError(
                    f"profile job {pjob} failed (exit {progress.exit_code}); log: {remote.job_dir(pjob)}/log"
                )
            return
        if time.monotonic() >= deadline:
            raise VsbenchError(f"profile job {pjob} is still running; pull its reports later from {node}:{where}")
        time.sleep(2)


def _finalize_search(cluster: str, state: State, out: _Outcome) -> Finalized:
    view = {**state, **(out.job["params"].get("snapshot") or {})}
    sections = {section["name"]: section for section in out.sections}
    records = []
    for item in out.job["params"]["steps"]:
        warmup = sections.get(item["warmup"]) if item["warmup"] else None
        if warmup is not None and warmup["exit"] != 0:
            records.append(_search_record(cluster, view, out, item, warmup))
            break
        if item["name"] in sections:
            records.append(_search_record(cluster, view, out, item, sections[item["name"]]))
    return records, None, None
