# Copyright 2026-present ScyllaDB
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.1

"""SSH to cluster nodes: ssh config, commands, file transfer and detached jobs.

Remote commands are shell strings run by the node's login shell; every value put
into one is shlex-quoted. Long work runs as a detached systemd unit (`job_*`).
"""

from __future__ import annotations

import base64
import concurrent.futures
import functools
import hashlib
import ipaddress
import json
import os
import re
import secrets
import shlex
import subprocess
import sys
import threading
import time
import urllib.request
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import config, proc
from . import state as st
from .guard import (  # noqa: F401  (re-exported: the cli calls remote.is_dangerous)
    POWER_OFF_REASON,
    TTL_TAMPER_REASON,
    is_dangerous,
    is_ttl_tamper,
    refusal_reason,
)
from .proc import StillRunning, VsbenchError
from .state import ClusterPaths, State

SSH_USER = "ubuntu"
SSH_FAILED = 255  # ssh's own exit code for connection/authentication failures
CONTROL_PREFIX = "vsb-"
# ControlPath `<dir>/vsb-%C`: %C is 40 hex chars and ssh appends ".<16 chars>"
# while binding; keep the socket path < 100 bytes (sun_path: 104 macOS, 108 Linux).
MAX_CONTROL_PATH = 100
_CONTROL_EXTRA = 1 + len(CONTROL_PREFIX) + 40 + 17
CHECKIP_URL = "https://checkip.amazonaws.com"
MAX_PARALLEL = 16
MAX_SCRIPT_BYTES = 100_000  # node scripts travel as one argv string (limit 128 KiB)
LARGE_UPLOAD_BYTES = 8 * 1024 * 1024
WAIT_SSH_ATTEMPT_TIMEOUT_S = 30
WAIT_SSH_RETRY_S = 5

JOB_RUNNER = "job-run.sh"
JOB_UNIT_PREFIX = "vsbench-job-"
JOB_POLL_SECONDS = 2.0
JOB_POLL_CHUNK_BYTES = 4 * 1024 * 1024
JOB_STOP_TIMEOUT_S = 60
JOB_CANCELLED_EXIT = 143
MAX_POLL_FAILURES = 3  # consecutive failed polls tolerated by job_follow
_ACTIVE_STATES = ("active", "activating", "deactivating", "reloading", "refreshing")

_ENV_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_NODE_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
_JOB_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]*$")
_JOB_KIND_RE = re.compile(r"^[a-z][a-z0-9-]*$")
_SCRIPT_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
_MODE_RE = re.compile(r"^[0-7]{3,4}$")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_INSTANCE_ID_RE = re.compile(r"^i-[0-9a-f]+$")
JOB_NOFILE = 1048576  # RLIMIT_NOFILE of jobs: search-http keeps one socket per concurrent request


# --- ssh config ---------------------------------------------------------------
def control_dir() -> str:
    """Directory for ControlMaster sockets: $XDG_RUNTIME_DIR when usable, else /tmp."""
    candidate = os.environ.get("XDG_RUNTIME_DIR", "").rstrip("/")
    fits = len(os.fsencode(candidate)) + _CONTROL_EXTRA < MAX_CONTROL_PATH
    return candidate if candidate and fits and os.path.isabs(candidate) and os.path.isdir(candidate) else "/tmp"


def _config_value(path: str, raw_suffix: str = "") -> str:
    """Render a path for ssh_config: `%` escaped, double-quoted when it has blanks."""
    if any(c in path for c in '"\n\r') or "${" in path:
        raise VsbenchError(f"unsupported path for the ssh config: {path!r}", "use a plain VSBENCH_HOME path")
    value = path.replace("%", "%%") + raw_suffix
    return f'"{value}"' if any(c.isspace() for c in value) else value


def _host_block(node: st.Node, identity: str, known_hosts: str, control: str) -> list[str]:
    name, ip, instance_id = node["name"], str(node["public_ip"]), str(node["instance_id"])
    try:
        ipaddress.ip_address(ip)
    except ValueError as err:
        raise VsbenchError(f"invalid public IP for node {name!r} in state: {ip!r}") from err
    if not _NODE_RE.fullmatch(name) or not _INSTANCE_ID_RE.fullmatch(instance_id):
        raise VsbenchError(f"invalid node in state: {name!r} ({instance_id!r})")
    options = [f"HostName {ip}", f"User {SSH_USER}", f"IdentityFile {identity}", "IdentitiesOnly yes"]
    options += [f"UserKnownHostsFile {known_hosts}", f"HostKeyAlias {instance_id}", "StrictHostKeyChecking accept-new"]
    options += ["ServerAliveInterval 30", "ServerAliveCountMax 4", "ConnectTimeout 10", "ControlMaster auto"]
    options += [f"ControlPath {control}", "ControlPersist 10m", "LogLevel ERROR"]
    return [f"Host {name}", *(f"  {option}" for option in options), ""]


def ssh_config_text(state: State, paths: ClusterPaths) -> str:
    """The cluster's ssh config: one Host block per node that has a public IP."""
    identity = _config_value(str(paths.ssh_key))
    known_hosts = _config_value(str(paths.known_hosts))
    control = _config_value(control_dir(), f"/{CONTROL_PREFIX}%C")
    lines = [f"# Generated by vsbench from the state of cluster '{state.get('cluster', '')}'; do not edit.", ""]
    for node in st.nodes(state):
        if not node.get("public_ip") or not node.get("instance_id"):
            lines += [f"# {node['name']}: no public IP yet", ""]
            continue
        lines += _host_block(node, identity, known_hosts, control)
    return "\n".join(lines)


def write_ssh_config(cluster: str, state: State) -> Path:
    paths = st.paths(cluster)
    paths.ssh_dir.mkdir(parents=True, exist_ok=True)
    os.chmod(paths.ssh_dir, 0o700)
    proc.atomic_write(paths.ssh_config, ssh_config_text(state, paths), mode=0o600)
    return paths.ssh_config


def config_hosts(text: str) -> list[str]:
    return [line.split()[1] for line in text.splitlines() if line.startswith("Host ") and len(line.split()) > 1]


def _config_control_dir(text: str) -> str | None:
    for line in text.splitlines():
        parts = line.strip().split(None, 1)
        if len(parts) == 2 and parts[0] == "ControlPath":
            directory = parts[1].strip('"').rsplit("/", 1)[0]
            return directory.replace("%%", "%") or "/"
    return None


def _config_usable(cfg: Path, node: str | None) -> bool:
    if not cfg.exists():
        return False
    text = cfg.read_text()
    if node is not None and node not in config_hosts(text):
        return False
    directory = _config_control_dir(text)
    return directory is None or os.path.isdir(directory)


def _ssh_config_for(cluster: str, node: str | None = None) -> Path:
    """The cluster's ssh config; rewritten from state when missing or stale."""
    cfg = st.paths(cluster).ssh_config
    if not _config_usable(cfg, node):
        current = st.load(cluster)
        if current and current.get("nodes"):
            write_ssh_config(cluster, current)
    if not cfg.exists():
        raise VsbenchError(f"cluster '{cluster}' has no ssh config", f"create it with: vsbench -c {cluster} up")
    if node is not None and node not in config_hosts(cfg.read_text()):
        raise VsbenchError(
            f"node '{node}' is not reachable over ssh (unknown node or no public IP)",
            f"list the nodes with: vsbench -c {cluster} status --refresh",
        )
    return cfg


def _base(cluster: str, node: str | None, multiplex: bool) -> list[str]:
    cmd = ["ssh", "-F", str(_ssh_config_for(cluster, node))]
    if not multiplex:
        cmd += ["-o", "ControlMaster=no", "-o", "ControlPath=none"]
    return cmd


def ssh_base(cluster: str, multiplex: bool = True) -> list[str]:
    """`ssh -F <cluster config>` (+ options that bypass the ControlMaster)."""
    return _base(cluster, None, multiplex)


# --- failure hints --------------------------------------------------------------
@functools.lru_cache(maxsize=1)
def current_public_ip() -> str | None:
    """This machine's public IPv4 address (cached per process); None when unknown."""
    try:
        with urllib.request.urlopen(CHECKIP_URL, timeout=5) as response:
            text = response.read(64).decode("ascii", "replace").strip()
        ipaddress.ip_address(text)
    except (OSError, ValueError) as err:
        proc.debug(f"checkip failed: {err}")
        return None
    return text


def _timeout_hint(cluster: str) -> str:
    try:
        recorded = ((st.load(cluster) or {}).get("aws") or {}).get("operator_cidr")
    except (VsbenchError, ValueError, OSError):
        recorded = None
    current = current_public_ip()
    if current and recorded and f"{current}/32" != recorded:
        return (
            f"your public IP changed ({recorded} -> {current}/32); allow the new one: vsbench -c {cluster} refresh-ip"
        )
    return (
        f"no answer on port 22: is the node running (vsbench -c {cluster} status --refresh)? "
        f"after a VPN/WARP switch run: vsbench -c {cluster} refresh-ip"
    )


def ssh_failure_hint(cluster: str, stderr: str) -> str | None:
    """A hint for an ssh/scp failure, based on its stderr."""
    text = stderr.lower()
    if "timed out" in text:
        return _timeout_hint(cluster)
    if "connection refused" in text:
        return f"sshd refused the connection (node rebooting?); retry or check: vsbench -c {cluster} status --refresh"
    if "permission denied" in text:
        return f"the node rejected the cluster key {st.paths(cluster).ssh_key} (cluster created elsewhere?)"
    if "host key verification failed" in text or "host identification has changed" in text:
        return f"the host key changed for this instance id; see {st.paths(cluster).known_hosts}"
    if "could not resolve hostname" in text or "no route to host" in text or "network is unreachable" in text:
        return f"check your network and the node addresses (vsbench -c {cluster} status --refresh)"
    return None


def is_ssh_failure(result: subprocess.CompletedProcess[str]) -> bool:
    """True when ssh itself failed (connection/authentication), not the remote command."""
    return result.returncode == SSH_FAILED


def _short(command: str, limit: int = 160) -> str:
    flat = " ".join(command.split())
    return flat if len(flat) <= limit else flat[: limit - 3] + "..."


def _remote_error(cluster: str, node: str, remote: str, result: subprocess.CompletedProcess[str]) -> VsbenchError:
    detail = proc.tail((result.stderr or result.stdout or "").strip(), 30)
    suffix = f"\n{detail}" if detail else ""
    if result.returncode == SSH_FAILED:
        message = f"ssh to {node} failed (exit 255): {_short(remote)}{suffix}"
        return VsbenchError(message, ssh_failure_hint(cluster, result.stderr or ""))
    return VsbenchError(f"{node}: remote command failed (exit {result.returncode}): {_short(remote)}{suffix}")


# --- commands -----------------------------------------------------------------------
def _env_words(env: Mapping[str, str] | None) -> list[str]:
    words = []
    for key, value in (env or {}).items():
        if not _ENV_KEY_RE.fullmatch(key):
            raise VsbenchError(f"invalid environment variable name: {key!r}")
        words.append(f"{key}={shlex.quote(str(value))}")
    return words


def wrap_command(command: str, *, env: Mapping[str, str] | None = None, sudo: bool = False) -> str:
    """Prefix a command with `sudo -n` / `env K=V...` (quoted), as `bash -c <command>` so
    pipes and `&&` stay inside the sudo/env scope."""
    words = _env_words(env)
    if not words and not sudo:
        return command
    prefix = (["sudo", "-n"] if sudo else []) + (["env", *words] if words else [])
    return " ".join([*prefix, "bash", "-c", shlex.quote(command)])


def _check_node_name(node: str) -> None:
    if not _NODE_RE.fullmatch(node):
        raise VsbenchError(f"invalid node name: {node!r}")


def _ssh(
    cluster: str, node: str, remote: str, *, input: str | None, check: bool, timeout: float | None, multiplex: bool
) -> subprocess.CompletedProcess[str]:
    _check_node_name(node)
    argv = _base(cluster, node, multiplex) + ["-o", "BatchMode=yes"]
    if input is None:
        argv.append("-n")  # never read the caller's stdin
    argv += ["--", node, remote]
    try:
        result = proc.run(argv, input=input, check=False, timeout=timeout)
    except VsbenchError as err:
        if isinstance(err.__cause__, subprocess.TimeoutExpired):
            raise VsbenchError(f"{node}: remote command timed out after {timeout:g}s: {_short(remote)}") from err
        raise
    if check and result.returncode != 0:
        raise _remote_error(cluster, node, remote, result)
    return result


def run(
    cluster: str,
    node: str,
    command: str,
    *,
    input: str | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: dict[str, str] | None = None,
    sudo: bool = False,
    multiplex: bool = True,
) -> subprocess.CompletedProcess[str]:
    """Run a shell command string on a node (output captured). With check, a non-zero
    exit raises VsbenchError (ssh failures get a hint); see also `is_ssh_failure`."""
    remote = wrap_command(command, env=env, sudo=sudo)
    return _ssh(cluster, node, remote, input=input, check=check, timeout=timeout, multiplex=multiplex)


def _local_script(script_name: str) -> Path:
    if not _SCRIPT_NAME_RE.fullmatch(script_name):
        raise VsbenchError(f"invalid node script name: {script_name!r}")
    path = config.NODE_SCRIPTS_DIR / script_name
    if not path.is_file():
        raise VsbenchError(f"node script not found: {path}")
    return path


def run_script(
    cluster: str,
    node: str,
    script_name: str,
    env: dict[str, str],
    *,
    sudo: bool = True,
    check: bool = True,
    timeout: float | None = None,
) -> subprocess.CompletedProcess[str]:
    """Run SKILL/node/<script_name> on a node with `env`. It is sent over stdin and read
    whole before it runs (`bash -c "$(cat)"`), so its commands cannot eat the rest."""
    text = _local_script(script_name).read_text()
    if len(text.encode()) > MAX_SCRIPT_BYTES:
        raise VsbenchError(f"node script too large to send inline: {script_name}")
    command = f'exec bash -c "$(cat)" {shlex.quote(script_name)}'
    remote = wrap_command(command, env=env, sudo=sudo)
    return _ssh(cluster, node, remote, input=text, check=check, timeout=timeout, multiplex=True)


def _combined_error(errors: dict[str, VsbenchError], total: int) -> VsbenchError:
    lines = [f"command failed on {len(errors)} of {total} nodes:"]
    for name, err in errors.items():
        lines.append(f"  {name}: " + str(err).strip().replace("\n", "\n    "))
    hint = next((err.hint for err in errors.values() if err.hint), None)
    return VsbenchError("\n".join(lines), hint)


def run_many(cluster: str, nodes: list[str], command: str, **kw: Any) -> dict[str, subprocess.CompletedProcess[str]]:
    """`run` on nodes in parallel; results in input order. With check, failures are raised
    together; without, a node whose call raised (e.g. timeout) gets exit 255 + the error."""
    if not nodes:
        return {}
    check = kw.pop("check", True)
    results: dict[str, subprocess.CompletedProcess[str]] = {}
    errors: dict[str, VsbenchError] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(len(nodes), MAX_PARALLEL)) as pool:
        futures = {pool.submit(run, cluster, name, command, check=check, **kw): name for name in nodes}
        for future in concurrent.futures.as_completed(futures):
            name = futures[future]
            try:
                results[name] = future.result()
            except VsbenchError as err:
                if check:
                    errors[name] = err
                else:
                    text = str(err) + (f"\nhint: {err.hint}" if err.hint else "")
                    results[name] = subprocess.CompletedProcess([name], SSH_FAILED, "", text)
    if errors:
        raise _combined_error({n: errors[n] for n in nodes if n in errors}, len(nodes))
    return {name: results[name] for name in nodes}


def interactive(cluster: str, node: str, command: list[str] | None) -> int:
    """ssh to a node with inherited stdin/stdout/stderr; returns the exit code."""
    _check_node_name(node)
    argv = _base(cluster, node, True)
    if command and sys.stdin.isatty() and sys.stdout.isatty():
        argv.append("-t")
    argv += ["--", node, *(command or [])]
    code = proc.run(argv, check=False, capture=False).returncode
    if code == SSH_FAILED:
        proc.warn(f"ssh {node} exited with 255; if your public IP changed, run: vsbench -c {cluster} refresh-ip")
    return code


# --- files ---------------------------------------------------------------------------
def sha256_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def remote_sha256(cluster: str, node: str, path: str, *, sudo: bool = False) -> str | None:
    """sha256 of a file on a node; None when it does not exist or is unreadable."""
    result = run(cluster, node, f"sha256sum -- {shlex.quote(path)} 2>/dev/null | cut -d' ' -f1; true", sudo=sudo)
    value = result.stdout.strip()
    return value if _SHA256_RE.fullmatch(value) else None


def _scp(cluster: str, node: str, args: list[str]) -> None:
    argv = ["scp", "-F", str(_ssh_config_for(cluster, node)), "-q", "-o", "BatchMode=yes", "--", *args]
    result = proc.run(argv, check=False)
    if result.returncode != 0:
        detail = proc.tail((result.stderr or "").strip(), 10)
        message = f"scp {' '.join(args)} failed (exit {result.returncode})" + (f"\n{detail}" if detail else "")
        raise VsbenchError(message, ssh_failure_hint(cluster, result.stderr or ""))


def install_command(staging: str, dest: str, mode: str, digest: str) -> str:
    """Shell: install an uploaded file next to `dest`, then rename it over `dest` only when
    its sha256 matches (exit 3 otherwise), so `dest` is never partially written."""
    q = shlex.quote
    src, stage, target = q(staging), q(f"{dest}.vsbench-tmp"), q(dest)
    return "; ".join(
        [
            "set -e",
            f"install -D -m {mode} -- {src} {stage} || {{ rm -f -- {src}; exit 1; }}",
            f"rm -f -- {src}",
            f"got=$(sha256sum -- {stage} | cut -d' ' -f1)",
            f'if [ "$got" != {digest} ]; then rm -f -- {stage}; '
            f'echo sha256 mismatch for {target}: expected {digest}, got "$got" >&2; exit 3; fi',
            f"mv -f -- {stage} {target}",
        ]
    )


def upload(cluster: str, node: str, local: Path, remote_path: str, *, sudo: bool = False, mode: str = "0755") -> None:
    """Copy a file to `remote_path` (parents created), verified by sha256. Upload job files
    without sudo: job directories must stay owned by ubuntu."""
    local = Path(local)
    if not local.is_file():
        raise VsbenchError(f"local file not found: {local}")
    if not _MODE_RE.fullmatch(mode):
        raise VsbenchError(f"invalid file mode {mode!r}", "use octal digits, e.g. 0755")
    if not remote_path or remote_path.endswith("/") or any(c in remote_path for c in "\n\r\0"):
        raise VsbenchError(f"invalid remote path {remote_path!r}", "give the full path of the target file")
    size = local.stat().st_size
    if size >= LARGE_UPLOAD_BYTES:
        proc.log(f"uploading {local.name} ({size / 1e6:.0f} MB) to {node}:{remote_path}")
    digest = sha256_file(local)
    staging = f"/tmp/vsbench-upload-{secrets.token_hex(8)}"
    _scp(cluster, node, [str(local.resolve()), f"{node}:{staging}"])
    run(cluster, node, install_command(staging, remote_path, mode, digest), sudo=sudo)


def download(cluster: str, node: str, remote_path: str, local: Path) -> None:
    """Copy a file from a node; `local` is replaced atomically."""
    local = Path(local)
    local.parent.mkdir(parents=True, exist_ok=True)
    partial = local.parent.resolve() / f".{local.name}.part-{secrets.token_hex(4)}"
    try:
        _scp(cluster, node, [f"{node}:{remote_path}", str(partial)])
        os.replace(partial, local)
    finally:
        if partial.exists():
            partial.unlink()


_ENSURED: set[tuple[str, str, str, str]] = set()
_ENSURED_LOCK = threading.Lock()


def ensure_script(cluster: str, node: str, script_name: str) -> str:
    """Make NODE_SCRIPTS/<script_name> on the node match SKILL/node/<script_name>."""
    local = _local_script(script_name)
    remote_path = f"{config.NODE_SCRIPTS}/{script_name}"
    key = (cluster, node, script_name, sha256_file(local))
    with _ENSURED_LOCK:
        if key in _ENSURED:
            return remote_path
    if remote_sha256(cluster, node, remote_path) != key[3]:
        proc.debug(f"{node}: installing {remote_path}")
        upload(cluster, node, local, remote_path, sudo=True, mode="0755")
    with _ENSURED_LOCK:
        _ENSURED.add(key)
    return remote_path


# --- connectivity / http ----------------------------------------------------------
def wait_ssh(cluster: str, node: str, timeout_s: int) -> None:
    """Poll until ssh to the node works (no ControlMaster, so no stale group set)."""
    _check_node_name(node)
    _ssh_config_for(cluster, node)  # configuration errors fail fast
    deadline = time.monotonic() + timeout_s
    last = ""
    while True:
        try:
            result = run(cluster, node, "true", check=False, timeout=WAIT_SSH_ATTEMPT_TIMEOUT_S, multiplex=False)
            if result.returncode == 0:
                return
            last = (result.stderr or "").strip()
        except VsbenchError as err:
            last = str(err)
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            detail = f": {proc.tail(last, 5)}" if last else ""
            raise VsbenchError(f"{node}: ssh not reachable after {timeout_s}s{detail}", ssh_failure_hint(cluster, last))
        proc.debug(f"{node}: ssh not ready yet: {proc.tail(last, 1)}")
        time.sleep(min(WAIT_SSH_RETRY_S, remaining))


def reset_master(cluster: str, node: str) -> None:
    """Close the node's ControlMaster (`ssh -O exit`); errors are ignored."""
    try:
        proc.run([*ssh_base(cluster), "-O", "exit", "--", node], check=False, timeout=15)
    except VsbenchError as err:
        proc.debug(f"{node}: ssh -O exit: {err}")


def http_get(cluster: str, node: str, url: str, timeout: float = 10) -> str:
    """GET a URL from the node itself (`curl -fsS`); raises on HTTP errors."""
    if not url.startswith(("http://", "https://")):
        raise VsbenchError(f"invalid URL {url!r}")
    command = f"curl -fsS -g --max-time {timeout:g} {shlex.quote(url)}"
    result = run(cluster, node, command, check=False, timeout=timeout + 30)
    if result.returncode != 0:
        if is_ssh_failure(result):
            raise _remote_error(cluster, node, command, result)
        detail = proc.tail((result.stderr or "").strip(), 5)
        raise VsbenchError(f"{node}: GET {url} failed (curl exit {result.returncode}): {detail}")
    return result.stdout


def http_json(cluster: str, node: str, url: str, timeout: float = 10) -> Any:
    text = http_get(cluster, node, url, timeout)
    try:
        return json.loads(text)
    except json.JSONDecodeError as err:
        raise VsbenchError(f"{node}: GET {url} returned invalid JSON: {text[:200]!r}") from err


def run_bytes(cluster: str, node: str, command: str, *, timeout: float | None = None) -> bytes:
    """Run a shell command and return its raw stdout bytes (sent base64-encoded)."""
    remote = "bash -o pipefail -c " + shlex.quote(f"({command}) | base64 -w0")
    result = run(cluster, node, remote, timeout=timeout)
    return _b64decode(result.stdout, node)


def _b64decode(text: str, node: str) -> bytes:
    try:
        return base64.b64decode(text.strip(), validate=True)
    except ValueError as err:
        raise VsbenchError(f"{node}: garbled output from the node: {text[:100]!r}") from err


# --- detached jobs ------------------------------------------------------------------
@dataclass(frozen=True)
class JobProgress:
    """One poll of a job: new_text = complete log lines after the polled offset (all of
    the rest once it ended); offset = next byte offset; running = unit active;
    pending = more log than one poll returns is waiting (poll again right away)."""

    new_text: str
    offset: int
    exit_code: int | None
    ended_at: str | None
    running: bool = False
    pending: bool = False

    @property
    def done(self) -> bool:
        return self.exit_code is not None and not self.pending

    @property
    def lost(self) -> bool:
        """The unit is gone but no exit code was recorded (SIGKILL, OOM, reboot)."""
        return self.exit_code is None and not self.running


class JobNotFound(VsbenchError):
    pass


def new_job_id(kind: str) -> str:
    """`<utc yyyymmddThhmmssZ>-<kind>-<4 hex>`, e.g. 20261006T101530Z-search-1a2b."""
    if not _JOB_KIND_RE.fullmatch(kind):
        raise VsbenchError(f"invalid job kind {kind!r}")
    return f"{proc.utcnow().strftime('%Y%m%dT%H%M%SZ')}-{kind}-{secrets.token_hex(2)}"


def _check_job_id(job_id: str) -> None:
    if not _JOB_ID_RE.fullmatch(job_id):
        raise VsbenchError(f"invalid job id {job_id!r}")


def job_unit(job_id: str) -> str:
    _check_job_id(job_id)
    return f"{JOB_UNIT_PREFIX}{job_id}.service"


def job_dir(job_id: str) -> str:
    _check_job_id(job_id)
    return f"{config.NODE_JOBS}/{job_id}"


def job_start(
    cluster: str,
    node: str,
    job_id: str,
    argv: list[str] | None = None,
    script: str | None = None,
    env: dict[str, str] | None = None,
) -> None:
    """Start `argv` (or `bash <remote script>`) as a detached systemd unit as ubuntu.

    Output goes to NODE_JOBS/<job_id>/log; see node/job-run.sh for the files.
    """
    _check_job_id(job_id)
    if (argv is None) == (script is None) or (argv is not None and not argv):
        raise VsbenchError("job_start needs exactly one of a non-empty argv or a script path")
    runner = ensure_script(cluster, node, JOB_RUNNER)
    words = ["sudo", "-n", "systemd-run", f"--unit={job_unit(job_id)}", f"--uid={SSH_USER}", f"--gid={SSH_USER}"]
    words += ["--collect", "--quiet", "--expand-environment=no", f"--property=WorkingDirectory={config.NODE_HOME}"]
    words += [f"--property=TimeoutStopSec={JOB_STOP_TIMEOUT_S}", f"--property=LimitNOFILE={JOB_NOFILE}"]
    for key, value in (env or {}).items():
        if not _ENV_KEY_RE.fullmatch(key):
            raise VsbenchError(f"invalid environment variable name: {key!r}")
        words.append(f"--setenv={key}={value}")
    words += [runner, job_id, *(["--script", script] if script is not None else ["--", *(argv or [])])]
    run(cluster, node, shlex.join(words), timeout=120)
    proc.debug(f"{node}: started job {job_id}")


def poll_command(job_id: str, offset: int, max_bytes: int) -> str:
    """Shell: print status fields, then the log from `offset` (base64). Unit state first,
    exit_code before the log, so with an exit_code the log read after it is complete."""
    directory, unit = shlex.quote(job_dir(job_id)), shlex.quote(job_unit(job_id))
    return "; ".join(
        [
            f"d={directory}",
            f'echo "active=$(systemctl is-active {unit} 2>/dev/null)"',
            'if [ -d "$d" ]; then echo present=1; else echo present=0; fi',
            'echo "exit_code=$(cat "$d/exit_code" 2>/dev/null)"',
            'echo "ended_at=$(cat "$d/ended_at" 2>/dev/null)"',
            'echo "size=$(stat -c %s "$d/log" 2>/dev/null || echo 0)"',
            f'echo "data=$(tail -c +{offset + 1} "$d/log" 2>/dev/null | head -c {max_bytes} | base64 -w0)"',
        ]
    )


def _int_or_none(text: str) -> int | None:
    return int(text) if re.fullmatch(r"-?\d+", text.strip()) else None


def parse_poll(stdout: str, offset: int, max_bytes: int, node: str = "node") -> tuple[JobProgress, bool]:
    """Parse `poll_command` output into (progress, job directory exists)."""
    fields: dict[str, str] = {}
    for line in stdout.splitlines():
        key, sep, value = line.partition("=")
        if sep:
            fields[key.strip()] = value.strip()
    running = fields.get("active", "") in _ACTIVE_STATES
    exit_code = _int_or_none(fields.get("exit_code", ""))
    size = _int_or_none(fields.get("size", "")) or 0
    raw = _b64decode(fields.get("data", ""), node)
    covered = offset + len(raw) >= size
    if (exit_code is not None or not running) and covered:
        keep = raw  # the log is final: deliver a trailing partial line too
    elif b"\n" in raw:
        keep = raw[: raw.rfind(b"\n") + 1]
    else:
        keep = raw if len(raw) >= max_bytes else b""  # one line longer than a chunk
    progress = JobProgress(
        new_text=keep.decode("utf-8", "replace"),
        offset=offset + len(keep),
        exit_code=exit_code,
        ended_at=fields.get("ended_at") or None,
        running=running,
        pending=not covered,
    )
    return progress, fields.get("present") == "1"


def job_poll(
    cluster: str, node: str, job_id: str, offset: int, *, max_bytes: int = JOB_POLL_CHUNK_BYTES
) -> JobProgress:
    """Read the job's status and the log text after byte `offset`."""
    if offset < 0:
        raise VsbenchError(f"invalid log offset {offset}")
    result = run(cluster, node, poll_command(job_id, offset, max_bytes), timeout=120)
    progress, present = parse_poll(result.stdout, offset, max_bytes, node)
    if not present and not progress.running:
        raise JobNotFound(f"job {job_id} not found on {node}", f"list jobs with: vsbench -c {cluster} job list")
    return progress


def _poll_or_none(cluster: str, node: str, job_id: str, offset: int, failures: int) -> JobProgress | None:
    """job_poll that tolerates up to MAX_POLL_FAILURES consecutive transient failures."""
    try:
        return job_poll(cluster, node, job_id, offset)
    except JobNotFound:
        raise
    except VsbenchError as err:
        if failures + 1 > MAX_POLL_FAILURES:
            raise
        first = str(err).splitlines()[0] if str(err) else type(err).__name__
        proc.warn(f"polling job {job_id} on {node} failed ({failures + 1}/{MAX_POLL_FAILURES}), retrying: {first}")
        return None


def job_follow(
    cluster: str, node: str, job_id: str, timeout_s: int, on_line: Callable[[str], None], *, offset: int = 0
) -> int:
    """Stream log lines from `offset` to `on_line`; return the job's exit code. Raises
    StillRunning (exit 75) after `timeout_s`, VsbenchError when the job was lost."""
    deadline = time.monotonic() + max(0, timeout_s)
    failures = lost = 0
    while True:
        progress = _poll_or_none(cluster, node, job_id, offset, failures)
        failures = failures + 1 if progress is None else 0
        if progress is not None:
            for line in progress.new_text.splitlines():
                on_line(line)
            offset = progress.offset
            if progress.pending:
                continue
            if progress.exit_code is not None:
                return progress.exit_code
            lost = lost + 1 if progress.lost else 0
            if lost >= 2:  # seen twice in a row, so not a hiccup of `systemctl is-active`
                raise VsbenchError(
                    f"job {job_id} on {node} stopped without recording an exit code "
                    "(killed with SIGKILL, out of memory, or the node rebooted)",
                    f"inspect its log: vsbench -c {cluster} job logs {job_id}",
                )
            if lost:
                time.sleep(JOB_POLL_SECONDS)
                continue
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            waited = proc.format_duration(timeout_s) if timeout_s >= 60 else f"{max(0, timeout_s)}s"
            raise StillRunning(
                f"job {job_id} is still running on {node} after {waited}",
                f"it keeps running on the node; wait again with: vsbench -c {cluster} job wait {job_id}",
            )
        time.sleep(min(JOB_POLL_SECONDS, remaining))


def cancel_command(job_id: str) -> str:
    """Shell: stop the job's unit; record exit 143 if the job could not record one."""
    directory, unit = shlex.quote(job_dir(job_id)), shlex.quote(job_unit(job_id))
    return "; ".join(
        [
            f"d={directory}",
            f"was=$(systemctl is-active {unit} 2>/dev/null || true)",
            "rc=0",
            f"err=$(sudo -n systemctl stop {unit} 2>&1) || rc=$?",
            # 5: unit not loaded (already finished and collected).
            'if [ "$rc" != 0 ] && [ "$rc" != 5 ]; then echo "$err" >&2; exit "$rc"; fi',
            'if [ ! -d "$d" ]; then echo result=not-found; exit 0; fi',
            'if [ ! -e "$d/exit_code" ]; then '
            "t=$(date -u +%Y-%m-%dT%H:%M:%SZ); "
            'echo "=== VSBENCH JOB CANCELLED $t (no exit code recorded by the job)" >>"$d/log"; '
            'printf "%s\\n" "$t" >"$d/ended_at.tmp" && mv -f "$d/ended_at.tmp" "$d/ended_at"; '
            f'printf "%s\\n" {JOB_CANCELLED_EXIT} >"$d/exit_code.tmp" && mv -f "$d/exit_code.tmp" "$d/exit_code"; '
            "fi",
            'echo "result=$was"',
        ]
    )


def job_cancel(cluster: str, node: str, job_id: str) -> None:
    """Stop a job (`systemctl stop`); a no-op when it already ended."""
    result = run(cluster, node, cancel_command(job_id), timeout=JOB_STOP_TIMEOUT_S + 60)
    outcome = result.stdout.strip().rsplit("result=", 1)[-1].strip()
    if outcome == "not-found":
        raise JobNotFound(f"job {job_id} not found on {node}", f"list jobs with: vsbench -c {cluster} job list")
    if outcome in _ACTIVE_STATES:
        proc.log(f"job {job_id} on {node} stopped")
    else:
        proc.log(f"job {job_id} on {node} had already ended")


def job_log(cluster: str, node: str, job_id: str, tail: int | None) -> str:
    """The job's log (last `tail` lines, or all of it)."""
    if tail is not None and tail <= 0:
        return ""
    path = shlex.quote(f"{job_dir(job_id)}/log")
    reader = f"tail -n {int(tail)} -- {path}" if tail is not None else f"cat -- {path}"
    command = f"if [ ! -e {path} ]; then echo 'no log for job {job_id}' >&2; exit 4; fi; {reader}"
    return run_bytes(cluster, node, command).decode("utf-8", "replace")
