#!/bin/bash

set -e

echo running with: "$@"

usage() {
    echo "usage: $0 <docker-scylla-tag> <vector-store-bin-path> <vector-search-validator-bin-path>"
    exit 1
}

scylla_tag=$1
echo using scylla docker image: $scylla_tag
[[ -n $scylla_tag ]] || usage

vector_store=$(realpath $2)
echo using vector store binary: $vector_store
[[ -x $vector_store ]] || usage

validator=$(realpath $3)
echo using validator binary: $validator
[[ -x $validator ]] || usage

shift 3

dns_ip=127.0.1.1
base_ip=127.0.2.1

docker run --rm \
    --cap-add NET_ADMIN \
    --user root \
    --security-opt seccomp=unconfined \
    --dns=$dns_ip \
    --dns-search=. \
    --volume="$vector_store:/vector-store" \
    --volume="$validator:/vector-search-validator" \
    --network=none \
    --entrypoint=/vector-search-validator \
    $scylla_tag \
    run --dns-ip $dns_ip --base-ip $base_ip --scylla-default-conf /etc/scylla/scylla.yaml /usr/bin/scylla /vector-store $@
