name: Daily

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  daily-get-scylla-nightly-digest:
    uses: $/.github/workflows/get-scylla-nightly-digest.yml
    with:
      use-latest-scylla-nightly: true

  daily-build-validator:
    uses: $/.github/workflows/build-validator.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      ref: ${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

  daily-build-vector-store:
    uses: $/.github/workflows/build-vector-store.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      ref: ${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

  daily-get-validator-test-list:
    needs: ["daily-build-validator"]
    uses: $/.github/workflows/get-validator-test-list.yml
    with:
      os: ubuntu-latest
      arch: amd64

  daily-run-validator-tests:
    needs: ["daily-get-scylla-nightly-digest", "daily-build-vector-store", "daily-get-validator-test-list"]
    uses: $/.github/workflows/run-validator-tests.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      testcase: ${{ matrix.testcase }}
      ref: ${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        testcase: ${{fromJSON(needs.daily-get-validator-test-list.outputs.testcases)}}
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

  daily-save-scylla-nightly-digest:
    needs: daily-run-validator-tests
    runs-on: ubuntu-latest
    steps:
    - name: Download scylla-nightly digest artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: scylla-nightly-digest

    - name: Show scylla-nightly digest
      run: cat scylla-nightly-digest

    - name: Upload scylla-nightly digest artifact as artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: valid-scylla-nightly-digest
        path: scylla-nightly-digest
