name: Update Status - in review

on:
  pull_request:
    types: [ready_for_review, review_requested]

permissions:
  pull-requests: read

jobs:
  action-jira-status-update:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Jira Ticket IDs
        id: get-jira
        run: |
          echo "Searching for Jira ticket IDs in PR title and body..."

          title="${{ github.event.pull_request.title }}"
          body="${{ github.event.pull_request.body }}"

          echo "PR title: $title"
          echo "PR body: $body"

          > tickets.txt

          # Extract all Jira tickets from title (e.g. "ABC-123 DEF-456")
          echo "$title" | grep -oE '[A-Z]+-[0-9]+' >> tickets.txt

          # Extract from all 'Fixes' lines in the body (case-insensitive, flexible whitespace)
          echo "$body" | grep -iE '^Fixes[[:space:]]*:[[:space:]]*[A-Z]+-[0-9]+' | \
          grep -oE '[A-Z]+-[0-9]+' >> tickets.txt

          # Deduplicate and show final list
          sort -u tickets.txt > unique_tickets.txt
          cat unique_tickets.txt

          tickets_csv=$(paste -sd, unique_tickets.txt)
          echo "Final ticket list: $tickets_csv"
          echo "ticket-ids=$tickets_csv" >> $GITHUB_OUTPUT

      - name: Transition Jira Tickets to 'In Review'
        if: steps.get-jira.outputs.ticket-ids != ''
        env:
          JIRA_AUTH: ${{ secrets.USER_AND_KEY_FOR_JIRA_AUTOMATION }}
        run: |
          IFS=',' read -ra tickets <<< "${{ steps.get-jira.outputs.ticket-ids }}"
          for ticket_id in "${tickets[@]}"; do
            echo "Transitioning Jira ticket: $ticket_id"
            curl --fail -X POST \
              --url "https://scylladb.atlassian.net/rest/api/3/issue/${ticket_id}/transitions" \
              --user "$JIRA_AUTH" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              -d '{"transition": {"id": "121"}}'
          done
