name: Validator

on:
  push:
    branches:
    - 'master'

  pull_request:
    branches:
    - 'master'

  merge_group:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  validator-get-scylla-nightly-digest:
    uses: $/.github/workflows/get-scylla-nightly-digest.yml
    with:
      use-latest-scylla-nightly: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-latest-scylla-nightly') }}

  validator-build-validator:
    uses: $/.github/workflows/build-validator.yml
    with:
      os: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
      arch: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'amd64' || 'arm64' }}
      ref: ${{ github.sha }}

  validator-build-vector-store:
    uses: $/.github/workflows/build-vector-store.yml
    with:
      os: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
      arch: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'amd64' || 'arm64' }}
      ref: ${{ github.sha }}

  validator-get-validator-test-list:
    needs: ["validator-build-validator"]
    uses: $/.github/workflows/get-validator-test-list.yml
    with:
      os: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
      arch: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'amd64' || 'arm64' }}

  validator-run-validator-tests:
    needs: ["validator-get-scylla-nightly-digest", "validator-build-vector-store", "validator-get-validator-test-list"]
    uses: $/.github/workflows/run-validator-tests.yml
    with:
      os: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
      arch: ${{ contains(github.event.pull_request.labels.*.name, 'ci-use-amd64') && 'amd64' || 'arm64' }}
      testcase: ${{ matrix.testcase }}
      ref: ${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        testcase: ${{fromJSON(needs.validator-get-validator-test-list.outputs.testcases)}}

  validator-workflow-status:
    needs: ["validator-get-scylla-nightly-digest", "validator-build-validator", "validator-build-vector-store", "validator-get-validator-test-list", "validator-run-validator-tests"]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check workflow status
      run: |
        return_code=0

        if [[ "${{ needs.validator-get-scylla-nightly-digest.result }}" == "failure" ]]; then
          echo "validator-get-scylla-nightly-digest job failed"
          return_code=1
        fi

        if [[ "${{ needs.validator-build-validator.result }}" == "failure" ]]; then
          echo "validator-build-validator job failed"
          return_code=1
        fi

        if [[ "${{ needs.validator-build-vector-store.result }}" == "failure" ]]; then
          echo "validator-build-vector-store job failed"
          return_code=1
        fi

        if [[ "${{ needs.validator-get-validator-test-list.result }}" == "failure" ]]; then
          echo "validator-get-validator-test-list job failed"
          return_code=1
        fi

        if [[ "${{ needs.validator-run-validator-tests.result }}" == "failure" ]]; then
          echo "validator-run-validator-tests job failed"
          return_code=1
        fi

        if [[ $return_code -ne 0 ]]; then
          exit $return_code
        fi

        echo "All jobs succeeded"

